    - name: docker
      uses: pennsignals/publish_docker-compose@v0.1.0
      with:
        version: '0.2.6-rc.1' # optional
        docker_compose: 'docker-compose.yml' # required
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
